name: food_diary_ui_modern
description: Modern food diary UI with calorie tracking and meal cards
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter
  google_fonts: ^6.1.0
  percent_indicator: ^4.2.3
  image_picker: ^1.0.7
  provider: ^6.1.0
  intl: ^0.19.0



dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: "dairy.png"
  
flutter:
  uses-material-design: true
